In [1]:
# Question 1 Numpy Arrays
import numpy 
def arrays(arr):
    
    arr.reverse()
    numpy_arr = numpy.array(arr,float)
    return numpy_arr

    
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [2]:
#Question 2 Nump Shape and Reshape
import numpy as np


array = np.array(list(map(int, input().split())))
print(array.reshape(3, 3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#Question 3 Transpose and Flatten
import numpy

n,m=map(int,input().split())

lista=[list(map(int,input().split())) for i in range(n)]
a=numpy.array(lista)

print(numpy.transpose(a))
print(a.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [4]:
#Question 4 Concatenate
import numpy
P, N, M = map(int,input().split())
A = numpy.array([input().split() for _ in range(P)],int)
B = numpy.array([input().split() for _ in range(N)],int)
print(numpy.concatenate((A, B), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [5]:
#Question 5 Zeros and Ones
import numpy
dims = [int(x) for x in input().strip().split()]

print(numpy.zeros(tuple(dims), dtype = numpy.int))
print(numpy.ones(tuple(dims), dtype = numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [6]:
#Question 6 Eye and Identity
import numpy

numpy.set_printoptions(sign=' ')
print(numpy.eye(*map(int, input().split())))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [7]:
#Question 7 Array Mathemetics
import numpy




n, m = [int(x) for x in input().strip().split()]

a = numpy.array([[int(x) for x in input().strip().split()] for _ in range(n)])
b = numpy.array([[int(x) for x in input().strip().split()] for _ in range(n)])

print(a + b)
print(a - b)
print(a * b)
print(a // b)
print(a % b)
print(a**b)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [8]:
# Question 8 Floor,Ceil
import numpy as np

array = np.array(list(input().strip().split()), dtype = float)
                 
print(np.floor(array))
print(np.ceil(array))
print(np.rint(array))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [9]:
#Question 9 Sum and Prod
import numpy as np

n, m = [int(x) for x in input().strip().split()]
array = np.array([[int(x) for x in input().strip().split()] for _ in range(n)])
print(np.prod(np.sum(array, axis = 0)))

2 2
1 2
3 4
24


In [10]:
#Question 10 Min and Max
import numpy as np

n, m = [int(x) for x in input().strip().split()]
array = np.array([[int(x) for x in input().strip().split()] for _ in range(n)])
print(np.max(np.min(array, axis = 1)))

4 2
3 2
2 1
3 4
4 1
3


In [11]:
#Question 11 Mean,Var,Std
import numpy as np

n, m = [int(x) for x in input().strip().split()]
array = np.array([[int(x) for x in input().strip().split()] for _ in range(n)], dtype = float)
print(np.mean(array, axis = 1))
print(np.var(array, axis = 0))
print(np.std(array))

2 2
1 2
3 2
[ 1.5  2.5]
[ 1.  0.]
0.7071067811865476
